-- Phase 2b: auto-bucket companies on every write (enrichment RPC, backfill, manual).
-- Deterministic raw-industry -> Apollo-bucket map + size banding, applied by a BEFORE trigger so
-- no n8n change is needed. Unmapped non-empty industries fall to 'Other / Unknown'; null industry
-- or size leaves the bucket null. Mirrors app/scripts/lib/classify.mjs + company-industry-mapping.json.

create table if not exists public.company_industry_bucket_map (
  raw_industry text primary key,
  bucket text not null
);

insert into public.company_industry_bucket_map (raw_industry, bucket) values
  ('Computer Software', 'Software & IT Services'),
  ('Software Development', 'Software & IT Services'),
  ('Information Technology & Services', 'Software & IT Services'),
  ('IT Services and IT Consulting', 'Software & IT Services'),
  ('Data Infrastructure and Analytics', 'Software & IT Services'),
  ('Business Intelligence Platforms', 'Software & IT Services'),
  ('Embedded Software Products', 'Software & IT Services'),
  ('Mobile Computing Software Products', 'Software & IT Services'),
  ('Desktop Computing Software Products', 'Software & IT Services'),
  ('IT System Custom Software Development', 'Software & IT Services'),
  ('IT System Data Services', 'Software & IT Services'),
  ('IT System Design Services', 'Software & IT Services'),
  ('IT System Training and Support', 'Software & IT Services'),
  ('Digital Accessibility Services', 'Software & IT Services'),
  ('Artificial Intelligence', 'Software & IT Services'),
  ('Computer & Network Security', 'Cybersecurity'),
  ('Computer and Network Security', 'Cybersecurity'),
  ('Data Security Software Products', 'Cybersecurity'),
  ('Internet', 'Internet & Online Platforms'),
  ('Technology, Information and Internet', 'Internet & Online Platforms'),
  ('Internet Marketplace Platforms', 'Internet & Online Platforms'),
  ('Social Networking Platforms', 'Internet & Online Platforms'),
  ('Social Networking/Social Media', 'Internet & Online Platforms'),
  ('Blockchain Services', 'Internet & Online Platforms'),
  ('Computer Hardware', 'Computer Hardware & Networking'),
  ('Computer Hardware Manufacturing', 'Computer Hardware & Networking'),
  ('Computers and Electronics Manufacturing', 'Computer Hardware & Networking'),
  ('Computer Networking', 'Computer Hardware & Networking'),
  ('Computer Networking Products', 'Computer Hardware & Networking'),
  ('Consumer Electronics', 'Computer Hardware & Networking'),
  ('Communications Equipment Manufacturing', 'Computer Hardware & Networking'),
  ('Accessible Hardware Manufacturing', 'Computer Hardware & Networking'),
  ('Semiconductors', 'Semiconductors & Nanotech'),
  ('Semiconductor Manufacturing', 'Semiconductors & Nanotech'),
  ('Nanotechnology', 'Semiconductors & Nanotech'),
  ('Nanotechnology Research', 'Semiconductors & Nanotech'),
  ('Telecommunications', 'Telecommunications'),
  ('Telecommunications Carriers', 'Telecommunications'),
  ('Wireless', 'Telecommunications'),
  ('Wireless Services', 'Telecommunications'),
  ('Media and Telecommunications', 'Telecommunications'),
  ('Marketing & Advertising', 'Marketing, Advertising & PR'),
  ('Advertising Services', 'Marketing, Advertising & PR'),
  ('Marketing Services', 'Marketing, Advertising & PR'),
  ('Public Relations & Communications', 'Marketing, Advertising & PR'),
  ('Public Relations and Communications Services', 'Marketing, Advertising & PR'),
  ('Market Research', 'Marketing, Advertising & PR'),
  ('Events Services', 'Marketing, Advertising & PR'),
  ('Entertainment', 'Media & Entertainment'),
  ('Entertainment Providers', 'Media & Entertainment'),
  ('Media Production', 'Media & Entertainment'),
  ('Broadcast Media', 'Media & Entertainment'),
  ('Broadcast Media Production and Distribution', 'Media & Entertainment'),
  ('Online Media', 'Media & Entertainment'),
  ('Online Audio and Video Media', 'Media & Entertainment'),
  ('Internet News', 'Media & Entertainment'),
  ('Music', 'Media & Entertainment'),
  ('Musicians', 'Media & Entertainment'),
  ('Motion Pictures & Film', 'Media & Entertainment'),
  ('Movies, Videos, and Sound', 'Media & Entertainment'),
  ('Movies and Sound Recording', 'Media & Entertainment'),
  ('Animation', 'Media & Entertainment'),
  ('Animation and Post-production', 'Media & Entertainment'),
  ('Performing Arts', 'Media & Entertainment'),
  ('Performing Arts and Spectator Sports', 'Media & Entertainment'),
  ('Dance Companies', 'Media & Entertainment'),
  ('Fine Art', 'Media & Entertainment'),
  ('Artists and Writers', 'Media & Entertainment'),
  ('Photography', 'Media & Entertainment'),
  ('Computer Games', 'Media & Entertainment'),
  ('Mobile Gaming Apps', 'Media & Entertainment'),
  ('Technology, Information and Media', 'Media & Entertainment'),
  ('Publishing', 'Publishing & Information Services'),
  ('Internet Publishing', 'Publishing & Information Services'),
  ('Book and Periodical Publishing', 'Publishing & Information Services'),
  ('Book Publishing', 'Publishing & Information Services'),
  ('Newspapers', 'Publishing & Information Services'),
  ('Newspaper Publishing', 'Publishing & Information Services'),
  ('Writing & Editing', 'Publishing & Information Services'),
  ('Writing and Editing', 'Publishing & Information Services'),
  ('Information Services', 'Publishing & Information Services'),
  ('Business Content', 'Publishing & Information Services'),
  ('Libraries', 'Publishing & Information Services'),
  ('Translation & Localization', 'Publishing & Information Services'),
  ('Translation and Localization', 'Publishing & Information Services'),
  ('Management Consulting', 'Management Consulting & Business Services'),
  ('Business Consulting and Services', 'Management Consulting & Business Services'),
  ('Strategic Management Services', 'Management Consulting & Business Services'),
  ('Operations Consulting', 'Management Consulting & Business Services'),
  ('Professional Services', 'Management Consulting & Business Services'),
  ('Outsourcing/Offshoring', 'Management Consulting & Business Services'),
  ('Outsourcing and Offshoring Consulting', 'Management Consulting & Business Services'),
  ('Facilities Services', 'Management Consulting & Business Services'),
  ('Security & Investigations', 'Management Consulting & Business Services'),
  ('Security and Investigations', 'Management Consulting & Business Services'),
  ('Security Systems Services', 'Management Consulting & Business Services'),
  ('Office Administration', 'Management Consulting & Business Services'),
  ('Administrative and Support Services', 'Management Consulting & Business Services'),
  ('Financial Services', 'Financial Services & Banking'),
  ('Banking', 'Financial Services & Banking'),
  ('Investment Banking', 'Financial Services & Banking'),
  ('Investment Management', 'Financial Services & Banking'),
  ('Capital Markets', 'Financial Services & Banking'),
  ('Accounting', 'Financial Services & Banking'),
  ('Trusts and Estates', 'Financial Services & Banking'),
  ('Venture Capital & Private Equity', 'Venture Capital & Private Equity'),
  ('Venture Capital and Private Equity Principals', 'Venture Capital & Private Equity'),
  ('Insurance', 'Insurance'),
  ('Insurance Agencies and Brokerages', 'Insurance'),
  ('Law Practice', 'Legal Services'),
  ('Legal Services', 'Legal Services'),
  ('Alternative Dispute Resolution', 'Legal Services'),
  ('Human Resources', 'HR & Staffing'),
  ('Human Resources Services', 'HR & Staffing'),
  ('Staffing & Recruiting', 'HR & Staffing'),
  ('Staffing and Recruiting', 'HR & Staffing'),
  ('Executive Search Services', 'HR & Staffing'),
  ('Machinery', 'Industrial Machinery & Automation'),
  ('Machinery Manufacturing', 'Industrial Machinery & Automation'),
  ('Industrial Machinery Manufacturing', 'Industrial Machinery & Automation'),
  ('Industrial Automation', 'Industrial Machinery & Automation'),
  ('Automation Machinery Manufacturing', 'Industrial Machinery & Automation'),
  ('Mechanical Or Industrial Engineering', 'Industrial Machinery & Automation'),
  ('Robotics Engineering', 'Industrial Machinery & Automation'),
  ('Robot Manufacturing', 'Industrial Machinery & Automation'),
  ('Measuring and Control Instrument Manufacturing', 'Industrial Machinery & Automation'),
  ('HVAC and Refrigeration Equipment Manufacturing', 'Industrial Machinery & Automation'),
  ('Commercial and Industrial Machinery Maintenance', 'Industrial Machinery & Automation'),
  ('Agriculture, Construction, Mining Machinery Manufacturing', 'Industrial Machinery & Automation'),
  ('Electrical & Electronic Manufacturing', 'Electrical & Electronics Manufacturing'),
  ('Appliances, Electrical, and Electronics Manufacturing', 'Electrical & Electronics Manufacturing'),
  ('Electrical Equipment Manufacturing', 'Electrical & Electronics Manufacturing'),
  ('Audio and Video Equipment Manufacturing', 'Electrical & Electronics Manufacturing'),
  ('Chemicals', 'Chemicals & Plastics'),
  ('Chemical Manufacturing', 'Chemicals & Plastics'),
  ('Plastics', 'Chemicals & Plastics'),
  ('Plastics Manufacturing', 'Chemicals & Plastics'),
  ('Wholesale Chemical and Allied Products', 'Chemicals & Plastics'),
  ('Mining & Metals', 'Mining & Metals'),
  ('Mining', 'Mining & Metals'),
  ('Primary Metal Manufacturing', 'Mining & Metals'),
  ('Fabricated Metal Products', 'Mining & Metals'),
  ('Metal Treatments', 'Mining & Metals'),
  ('Spring and Wire Product Manufacturing', 'Mining & Metals'),
  ('Packaging & Containers', 'Packaging, Paper & Printing'),
  ('Packaging and Containers Manufacturing', 'Packaging, Paper & Printing'),
  ('Paper & Forest Products', 'Packaging, Paper & Printing'),
  ('Paper and Forest Product Manufacturing', 'Packaging, Paper & Printing'),
  ('Printing', 'Packaging, Paper & Printing'),
  ('Printing Services', 'Packaging, Paper & Printing'),
  ('Manufacturing', 'Manufacturing - Other'),
  ('Business Supplies & Equipment', 'Manufacturing - Other'),
  ('Furniture', 'Manufacturing - Other'),
  ('Furniture and Home Furnishings Manufacturing', 'Manufacturing - Other'),
  ('Office Furniture and Fixtures Manufacturing', 'Manufacturing - Other'),
  ('Textiles', 'Manufacturing - Other'),
  ('Textile Manufacturing', 'Manufacturing - Other'),
  ('Wood Product Manufacturing', 'Manufacturing - Other'),
  ('Railroad Manufacture', 'Manufacturing - Other'),
  ('Automotive', 'Automotive'),
  ('Motor Vehicle Manufacturing', 'Automotive'),
  ('Motor Vehicle Parts Manufacturing', 'Automotive'),
  ('Alternative Fuel Vehicle Manufacturing', 'Automotive'),
  ('Vehicle Repair and Maintenance', 'Automotive'),
  ('Retail Motor Vehicles', 'Automotive'),
  ('Aviation & Aerospace', 'Aviation & Aerospace'),
  ('Airlines/Aviation', 'Aviation & Aerospace'),
  ('Airlines and Aviation', 'Aviation & Aerospace'),
  ('Aviation and Aerospace Component Manufacturing', 'Aviation & Aerospace'),
  ('Space Research and Technology', 'Aviation & Aerospace'),
  ('Maritime', 'Maritime & Shipbuilding'),
  ('Maritime Transportation', 'Maritime & Shipbuilding'),
  ('Shipbuilding', 'Maritime & Shipbuilding'),
  ('Transportation/Trucking/Railroad', 'Transportation & Logistics'),
  ('Truck Transportation', 'Transportation & Logistics'),
  ('Transportation, Logistics, Supply Chain and Storage', 'Transportation & Logistics'),
  ('Logistics & Supply Chain', 'Transportation & Logistics'),
  ('Freight and Package Transportation', 'Transportation & Logistics'),
  ('Package/Freight Delivery', 'Transportation & Logistics'),
  ('Warehousing', 'Transportation & Logistics'),
  ('Warehousing and Storage', 'Transportation & Logistics'),
  ('Rail Transportation', 'Transportation & Logistics'),
  ('Ground Passenger Transportation', 'Transportation & Logistics'),
  ('Urban Transit Services', 'Transportation & Logistics'),
  ('Oil & Energy', 'Oil, Gas & Utilities'),
  ('Oil and Gas', 'Oil, Gas & Utilities'),
  ('Utilities', 'Oil, Gas & Utilities'),
  ('Electric Power Transmission, Control, and Distribution', 'Oil, Gas & Utilities'),
  ('Water Supply and Irrigation Systems', 'Oil, Gas & Utilities'),
  ('Renewables & Environment', 'Renewable Energy & Environment'),
  ('Environmental Services', 'Renewable Energy & Environment'),
  ('Services for Renewable Energy', 'Renewable Energy & Environment'),
  ('Renewable Energy Equipment Manufacturing', 'Renewable Energy & Environment'),
  ('Renewable Energy Power Generation', 'Renewable Energy & Environment'),
  ('Renewable Energy Semiconductor Manufacturing', 'Renewable Energy & Environment'),
  ('Solar Electric Power Generation', 'Renewable Energy & Environment'),
  ('Climate Technology Product Manufacturing', 'Renewable Energy & Environment'),
  ('Energy Technology', 'Renewable Energy & Environment'),
  ('Waste Collection', 'Renewable Energy & Environment'),
  ('Construction', 'Construction & Building Materials'),
  ('Building Construction', 'Construction & Building Materials'),
  ('Nonresidential Building Construction', 'Construction & Building Materials'),
  ('Building Materials', 'Construction & Building Materials'),
  ('Wholesale Building Materials', 'Construction & Building Materials'),
  ('Construction Hardware Manufacturing', 'Construction & Building Materials'),
  ('Glass, Ceramics & Concrete', 'Construction & Building Materials'),
  ('Glass, Ceramics and Concrete Manufacturing', 'Construction & Building Materials'),
  ('Architecture & Planning', 'Architecture, Design & Engineering'),
  ('Architecture and Planning', 'Architecture, Design & Engineering'),
  ('Design', 'Architecture, Design & Engineering'),
  ('Design Services', 'Architecture, Design & Engineering'),
  ('Graphic Design', 'Architecture, Design & Engineering'),
  ('Interior Design', 'Architecture, Design & Engineering'),
  ('Civil Engineering', 'Architecture, Design & Engineering'),
  ('Engineering Services', 'Architecture, Design & Engineering'),
  ('Surveying and Mapping Services', 'Architecture, Design & Engineering'),
  ('Real Estate', 'Real Estate'),
  ('Commercial Real Estate', 'Real Estate'),
  ('Leasing Non-residential Real Estate', 'Real Estate'),
  ('Leasing Residential Real Estate', 'Real Estate'),
  ('Hospital & Health Care', 'Healthcare & Hospitals'),
  ('Hospitals and Health Care', 'Healthcare & Hospitals'),
  ('Medical Practice', 'Healthcare & Hospitals'),
  ('Medical Practices', 'Healthcare & Hospitals'),
  ('Mental Health Care', 'Healthcare & Hospitals'),
  ('Alternative Medicine', 'Healthcare & Hospitals'),
  ('Medical and Diagnostic Laboratories', 'Healthcare & Hospitals'),
  ('Veterinary', 'Healthcare & Hospitals'),
  ('Services for the Elderly and Disabled', 'Healthcare & Hospitals'),
  ('Pharmaceuticals', 'Pharmaceuticals'),
  ('Pharmaceutical Manufacturing', 'Pharmaceuticals'),
  ('Biotechnology', 'Biotechnology'),
  ('Biotechnology Research', 'Biotechnology'),
  ('Medical Device', 'Medical Devices'),
  ('Medical Equipment Manufacturing', 'Medical Devices'),
  ('Research', 'Research & Development'),
  ('Research Services', 'Research & Development'),
  ('Consumer Goods', 'Consumer Goods'),
  ('Consumer Services', 'Consumer Goods'),
  ('Cosmetics', 'Consumer Goods'),
  ('Personal Care Product Manufacturing', 'Consumer Goods'),
  ('Personal Care Services', 'Consumer Goods'),
  ('Personal and Laundry Services', 'Consumer Goods'),
  ('Household Services', 'Consumer Goods'),
  ('Pet Services', 'Consumer Goods'),
  ('Arts & Crafts', 'Consumer Goods'),
  ('Sporting Goods', 'Consumer Goods'),
  ('Sporting Goods Manufacturing', 'Consumer Goods'),
  ('Tobacco', 'Consumer Goods'),
  ('Apparel & Fashion', 'Apparel, Fashion & Luxury'),
  ('Apparel Manufacturing', 'Apparel, Fashion & Luxury'),
  ('Retail Apparel and Fashion', 'Apparel, Fashion & Luxury'),
  ('Footwear Manufacturing', 'Apparel, Fashion & Luxury'),
  ('Fashion Accessories Manufacturing', 'Apparel, Fashion & Luxury'),
  ('Luxury Goods & Jewelry', 'Apparel, Fashion & Luxury'),
  ('Retail Luxury Goods and Jewelry', 'Apparel, Fashion & Luxury'),
  ('Retail', 'Retail & Wholesale'),
  ('Wholesale', 'Retail & Wholesale'),
  ('Import & Export', 'Retail & Wholesale'),
  ('Wholesale Import and Export', 'Retail & Wholesale'),
  ('Supermarkets', 'Retail & Wholesale'),
  ('Retail Groceries', 'Retail & Wholesale'),
  ('Food and Beverage Retail', 'Retail & Wholesale'),
  ('Online and Mail Order Retail', 'Retail & Wholesale'),
  ('Retail Office Equipment', 'Retail & Wholesale'),
  ('Retail Furniture and Home Furnishings', 'Retail & Wholesale'),
  ('Retail Health and Personal Care Products', 'Retail & Wholesale'),
  ('Retail Pharmacies', 'Retail & Wholesale'),
  ('Retail Art Supplies', 'Retail & Wholesale'),
  ('Retail Musical Instruments', 'Retail & Wholesale'),
  ('Retail Building Materials and Garden Equipment', 'Retail & Wholesale'),
  ('Retail Appliances, Electrical, and Electronic Equipment', 'Retail & Wholesale'),
  ('Wholesale Appliances, Electrical, and Electronics', 'Retail & Wholesale'),
  ('Wholesale Hardware, Plumbing, Heating Equipment', 'Retail & Wholesale'),
  ('Food Production', 'Food & Beverage'),
  ('Food & Beverages', 'Food & Beverage'),
  ('Food and Beverage Manufacturing', 'Food & Beverage'),
  ('Food and Beverage Services', 'Food & Beverage'),
  ('Beverage Manufacturing', 'Food & Beverage'),
  ('Dairy Product Manufacturing', 'Food & Beverage'),
  ('Wine & Spirits', 'Food & Beverage'),
  ('Restaurants', 'Food & Beverage'),
  ('Farming', 'Agriculture, Farming & Fishing'),
  ('Farming, Ranching, Forestry', 'Agriculture, Farming & Fishing'),
  ('Ranching', 'Agriculture, Farming & Fishing'),
  ('Dairy', 'Agriculture, Farming & Fishing'),
  ('Fishery', 'Agriculture, Farming & Fishing'),
  ('Fisheries', 'Agriculture, Farming & Fishing'),
  ('Hospitality', 'Hospitality, Travel & Leisure'),
  ('Leisure, Travel & Tourism', 'Hospitality, Travel & Leisure'),
  ('Travel Arrangements', 'Hospitality, Travel & Leisure'),
  ('Sightseeing Transportation', 'Hospitality, Travel & Leisure'),
  ('Gambling & Casinos', 'Hospitality, Travel & Leisure'),
  ('Gambling Facilities and Casinos', 'Hospitality, Travel & Leisure'),
  ('Museums & Institutions', 'Hospitality, Travel & Leisure'),
  ('Museums', 'Hospitality, Travel & Leisure'),
  ('Museums, Historical Sites, and Zoos', 'Hospitality, Travel & Leisure'),
  ('Health, Wellness & Fitness', 'Sports, Recreation & Wellness'),
  ('Wellness and Fitness Services', 'Sports, Recreation & Wellness'),
  ('Sports', 'Sports, Recreation & Wellness'),
  ('Spectator Sports', 'Sports, Recreation & Wellness'),
  ('Sports Teams and Clubs', 'Sports, Recreation & Wellness'),
  ('Recreational Facilities & Services', 'Sports, Recreation & Wellness'),
  ('Recreational Facilities', 'Sports, Recreation & Wellness'),
  ('Sports and Recreation Instruction', 'Sports, Recreation & Wellness'),
  ('Government Administration', 'Government & Public Sector'),
  ('Government Relations', 'Government & Public Sector'),
  ('Government Relations Services', 'Government & Public Sector'),
  ('Public Safety', 'Government & Public Sector'),
  ('Public Policy', 'Government & Public Sector'),
  ('Public Policy Offices', 'Government & Public Sector'),
  ('Public Health', 'Government & Public Sector'),
  ('Public Assistance Programs', 'Government & Public Sector'),
  ('Health and Human Services', 'Government & Public Sector'),
  ('Law Enforcement', 'Government & Public Sector'),
  ('Judiciary', 'Government & Public Sector'),
  ('Legislative Office', 'Government & Public Sector'),
  ('Legislative Offices', 'Government & Public Sector'),
  ('Executive Office', 'Government & Public Sector'),
  ('Executive Offices', 'Government & Public Sector'),
  ('International Affairs', 'Government & Public Sector'),
  ('International Trade & Development', 'Government & Public Sector'),
  ('International Trade and Development', 'Government & Public Sector'),
  ('Economic Programs', 'Government & Public Sector'),
  ('Community Development and Urban Planning', 'Government & Public Sector'),
  ('Defense & Space', 'Defense & Military'),
  ('Defense and Space Manufacturing', 'Defense & Military'),
  ('Military', 'Defense & Military'),
  ('Military and International Affairs', 'Defense & Military'),
  ('Armed Forces', 'Defense & Military'),
  ('Higher Education', 'Education'),
  ('Education', 'Education'),
  ('Education Management', 'Education'),
  ('Education Administration Programs', 'Education'),
  ('Primary/Secondary Education', 'Education'),
  ('Primary and Secondary Education', 'Education'),
  ('E-learning', 'Education'),
  ('E-Learning Providers', 'Education'),
  ('Professional Training & Coaching', 'Education'),
  ('Professional Training and Coaching', 'Education'),
  ('Technical and Vocational Training', 'Education'),
  ('Non-profit Organization Management', 'Nonprofit, NGO & Associations'),
  ('Non-profit Organizations', 'Nonprofit, NGO & Associations'),
  ('Civic & Social Organization', 'Nonprofit, NGO & Associations'),
  ('Civic and Social Organizations', 'Nonprofit, NGO & Associations'),
  ('Philanthropy', 'Nonprofit, NGO & Associations'),
  ('Philanthropic Fundraising Services', 'Nonprofit, NGO & Associations'),
  ('Fundraising', 'Nonprofit, NGO & Associations'),
  ('Think Tanks', 'Nonprofit, NGO & Associations'),
  ('Industry Associations', 'Nonprofit, NGO & Associations'),
  ('Professional Organizations', 'Nonprofit, NGO & Associations'),
  ('Religious Institutions', 'Nonprofit, NGO & Associations'),
  ('Community Services', 'Nonprofit, NGO & Associations'),
  ('Individual & Family Services', 'Nonprofit, NGO & Associations'),
  ('Individual and Family Services', 'Nonprofit, NGO & Associations'),
  ('Political Organization', 'Nonprofit, NGO & Associations'),
  ('Political Organizations', 'Nonprofit, NGO & Associations'),
  ('Program Development', 'Nonprofit, NGO & Associations'),
  ('Unknown', 'Other / Unknown'),
  ('N/A', 'Other / Unknown'),
  ('Holding Companies', 'Other / Unknown')
on conflict (raw_industry) do update set bucket = excluded.bucket;

create or replace function public.bucket_company_industry(p_raw text)
returns text language sql immutable as $$
  select case
    when p_raw is null or btrim(p_raw) = '' then null
    else coalesce(
      (select m.bucket from public.company_industry_bucket_map m
       where lower(m.raw_industry) = lower(btrim(p_raw)) limit 1),
      'Other / Unknown')
  end;
$$;

create or replace function public.bucket_company_size(p_size_range text, p_employee_count integer)
returns text language sql immutable as $$
  with n as (
    select case
      when p_employee_count is not null and p_employee_count > 0 then p_employee_count
      when p_size_range ~ '[0-9]' then greatest((substring(p_size_range from '[0-9]+'))::int, 1)
      else null
    end as cnt
  )
  select case
    when cnt is null then null
    when cnt <= 10 then '1-10'
    when cnt <= 50 then '11-50'
    when cnt <= 200 then '51-200'
    when cnt <= 500 then '201-500'
    when cnt <= 1000 then '501-1000'
    when cnt <= 5000 then '1001-5000'
    else '5000+'
  end from n;
$$;

create or replace function public.companies_set_buckets()
returns trigger language plpgsql as $$
begin
  new.industry_bucket := public.bucket_company_industry(new.industry);
  new.size_bucket := public.bucket_company_size(new.size_range, new.employee_count);
  return new;
end;
$$;

drop trigger if exists trg_companies_set_buckets on public.companies;
create trigger trg_companies_set_buckets
before insert or update of industry, size_range, employee_count on public.companies
for each row execute function public.companies_set_buckets();
